
--q 1
delimiter $$
CREATE FUNCTION FACT(X INT) RETURNS INT4
BEGIN
DECLARE FACT INT;
DECLARE I INT;
SET FACT=1 , I=1;

L1:LOOP
IF X>0 THEN 
SET FACT=FACT*I;
SET I=I+1;
SET X=X-1;
ITERATE L1;
ELSE
LEAVE L1;
END IF;
END LOOP L1;
RETURN FACT;
END$$

SELECT FACT(3);

-- q2
delimiter $$
CREATE FUNCTION PRIME(X INT) RETURNS VARCHAR(10)
BEGIN
	DECLARE M ,I INT;
	SET I=2;
	SET M=X/2;
	IF X=0 || X=1 THEN 
		RETURN 'NOT PRIME';
    ELSE
		L1: LOOP
		WHILE I<=M DO
			IF X%2=0 THEN 
				RETURN 'NOT PRIME';
				LEAVE L1;
				ELSE
				SET I=I+1;
				ITERATE L1;
			END IF;
	   END WHILE;
       RETURN 'PRIME';
	END LOOP L1;
	END IF;
END$$

DROP FUNCTION PRIME;
SELECT PRIME(5);