CREATE TABLE EMPLOYEEDETAILS
(EMPID INT PRIMARY KEY,FULLNAME VARCHAR(30),MANAGERID INT,DOJ DATE,CITY VARCHAR(20));

CREATE TABLE EMPLOYEESALARY
(EMPID INT PRIMARY KEY,PROJECT VARCHAR(30),SALARY INT4,VARIABLE INT3 ,constraint FK_KEY FOREIGN KEY (EMPID) REFERENCES EMPLOYEEDETAILS(EMPID));

INSERT INTO EMPLOYEEDETAILS VALUES(121,'John Snow',321,'2014-01-31','Toronta'),(321,'Walter White',986,'2015-01-30','California')
,(421,'Kuldeep Rana',876,'2016-11-27','New Delhi');

INSERT INTO EMPLOYEESALARY VALUES(121,'P1',8000,500),(321,'P2',10000,1000)
,(421,'P1',12000,0);
select * from EMPLOYEEDETAILS;
select * from EMPLOYEESALARY;

SELECT EMPID,FULLNAME FROM EMPLOYEEDETAILS WHERE MANAGERID=986;
SELECT DISTINCT PROJECT FROM EMPLOYEESALARY;
SELECT COUNT(EMPID) FROM EMPLOYEESALARY WHERE PROJECT='P1';
SELECT MAX(SALARY),MIN(SALARY),AVG(SALARY) FROM EMPLOYEESALARY;
SELECT  EMPID FROM  EMPLOYEESALARY WHERE SALARY BETWEEN 9000 AND 15000;
SELECT FULLNAME FROM EMPLOYEEDETAILS WHERE CITY='Toronta' AND MANAGERID=321;
SELECT FULLNAME FROM EMPLOYEEDETAILS WHERE CITY='California' OR MANAGERID=321;
SELECT * FROM EMPLOYEESALARY WHERE NOT  PROJECT='P1';
SET @VAR=1000;
SELECT SUM(SALARY) + @VAR FROM EMPLOYEESALARY ;
SELECT * FROM EMPLOYEEDETAILS WHERE FULLNAME LIKE '__hn%';